FROM public.ecr.aws/lambda/python:3.12

WORKDIR ${LAMBDA_TASK_ROOT}

COPY publisher-requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r publisher-requirements.txt

COPY src/ ${LAMBDA_TASK_ROOT}/

ARG APP_ENV=production
ARG PROJECT_NAME=hb-raw-data-pipeline
ARG RAW_FILES_DIR=/tmp
ARG LOG_LEVEL=INFO

ENV APP_ENV=${APP_ENV} \
    PROJECT_NAME=${PROJECT_NAME} \
    RAW_FILES_DIR=${RAW_FILES_DIR} \    
    LOG_LEVEL=${LOG_LEVEL}

CMD ["publisher.lambda_handler"]
